sonar.projectKey=clinica-dental-frontend
sonar.projectName=Clinica Dental Frontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts,cypress/e2e/**/*.cy.ts
sonar.exclusions=src/environments/**,cypress/fixtures/**,cypress/support/**
sonar.cpd.exclusions=cypress/fixtures/**,cypress/support/**,src/**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/clinica-dental-fronted/lcov.info
sonar.sourceEncoding=UTF-8
